[tool.poetry]
name = "app-test"
version = "0.1.0"
description = ""
authors = ["diego-insaurralde <diego_insaurralde@live.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
